name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  batch: true
  branches:
    include:
    - master
    - rel/*
pr:
- '*'
resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   thnetii
jobs:
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    common:
      allProjects: |
        [Ss]rc/*/*.csproj
        [Tt]est/*/*.csproj
    independantRuntime:
      pool:
        vmImage: windows-latest
      arguments:    '-p:NoNetFramework=false'
